# application.yml

spring:
    mail:
        default-endoding: UTF-8
        host: smtp.gmail.com
        username: gmail@gmail.com
        password: gmail@gmail.com
        port: 587
        properties: 
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        
        protocol: smtp
        test-connection: false
